version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mdconverter-api
    container_name: mdconverter-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__MdConverterDbContext}
      - Minio__Url=${MINIO__URL}
      - Minio__AccessKey=${MINIO__ACCESSKEY}
      - Minio__SecretKey=${MINIO__SECRETKEY}
      - Auth__Secretkey=${AUTH__SECRETKEY}
      - Auth__Expires=${AUTH__EXPIRES}
    depends_on:
      - postgres
      - minio
    networks:
      - mdconverter-network

  postgres:
    image: postgres:13
    container_name: mdconverter-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mdconverterdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mdconverter-network

  minio:
    image: minio/minio:latest
    container_name: mdconverter-minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO__ACCESSKEY}
      - MINIO_SECRET_KEY=${MINIO__SECRETKEY}
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - mdconverter-network

networks:
  mdconverter-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: